# This file is aimed to disable plugins cmoing from the
# default configuration
# You can do that using the following syntax:

#[[plugins]]
#repo = 'author/repo'

# example

# [[plugins]]
# repo = 'salsifis/vim-transpose'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'andymass/vim-tradewinds'
# [[plugins]]
# repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'

# [[plugins]]
# repo = 'garbas/vim-snipmate'

# [[plugins]]
# repo = 'GuillaumeFavelier/vim-snipmate-snippets'
